"""add client_event_id and focus sessions

Revision ID: 803f838d3969
Revises: 339f5d1471c9
Create Date: 2026-09-26 21:55:11.416810
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '803f838d3969'
down_revision: str | None = '339f5d1471c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED', 'COMPLETED', 'ABANDONED', name='focus_session_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('deviation_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_sessions_status'), 'focus_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_focus_sessions_task_id'), 'focus_sessions', ['task_id'], unique=False)
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    op.add_column('events', sa.Column('client_event_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_events_client_event_id'), 'events', ['client_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_client_event_id'), table_name='events')
    op.drop_column('events', 'client_event_id')
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    op.drop_index(op.f('ix_focus_sessions_task_id'), table_name='focus_sessions')
    op.drop_index(op.f('ix_focus_sessions_status'), table_name='focus_sessions')
    op.drop_table('focus_sessions')
    # ### end Alembic commands ###
